# Generated by Django 2.1.2 on 2018-11-10 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('barns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('barn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barns.Barn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sensordatapoint',
            name='barn',
        ),
        migrations.AddField(
            model_name='sensordatapoint',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barns.Sensor'),
            preserve_default=False,
        ),
    ]
