# Generated by Django 2.1.2 on 2018-11-10 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('barns', '0002_auto_20181110_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Alive'), (2, 'Dead')], default=1)),
                ('barn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barns.Barn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
