# Generated by Django 2.1.2 on 2018-11-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barns', '0004_auto_20181111_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatapoint',
            name='barn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barns.Barn'),
            preserve_default=False,
        ),
    ]
